[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "ca-certificates", "ttf-dejavu"]

[phases.install]
cmds = ["npm install", "cd client && npm install"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "node server/index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
